# Default Allay site configuration
base_url = "https://pkusoftwareengineeringteam.github.io/Axolotl-Wiki-Pages/"
title = "Axolotl Wiki"
theme = "Axolotl"
description = "Official Axolotl Wiki"
author = "Allay Developer"

[plugins.plugin_sort_page]
git = "https://github.com/PKUSoftwareEngineeringTeam/Allay"
tag = "plugin-sort-page-v0.1.0"
file = "plugin_sort_page.wasm"

[plugins.plugin_reading_time]
git = "https://github.com/PKUSoftwareEngineeringTeam/Allay"
tag = "plugin-reading-time-v0.1.1"
file = "plugin_reading_time.wasm"

[params]
title = "Axolotl Wiki"
subtitle = "Building the Future of Static Blogging."
author = "Allay 团队"
intro = "Building the Future of Static Blogging."
bio = "欢迎来到 Axolotl Wiki！我们致力于为您提供一个简洁、高效且易于使用的静态博客引擎。"
email = "www.allay@example.com"
location = "中国，北京"
github_repo = "https://github.com/PKUSoftwareEngineeringTeam/Axolotl-Wiki"

[params.links]
github = "https://github.com/PKUSoftwareEngineeringTeam"
twitter = "https://twitter.com/"
instagram = "https://www.instagram.com/"
weibo = "https://weibo.com/"

[params.footer]
year = 2024
note = "Why this name?... Minecraft."

[params.gitalk]
enable = true
client_id = "Ov23livxBGg30QbIUQse"
client_secret = 'a0f8e2c1678f075a9c1519e4b4f970356dd55c6c'
repo = "Axolotl-Wiki-Pages"
owner = "PKUSoftwareEngineeringTeam"
admin = "LeoDreamer2004"
title = "Axolotl Wiki Feedback"
language = "zh-CN"
